### PR TITLE
Updatedfont

### PR DESCRIPTION
**Pull request by gurjott**
added the button to change the font of the music player

### CODE REVIEW

**Comment by Tejas242** [comment]
Can you add a better styling to the font selector and move it to upper or bottom corner of the page(outside the music player container)

**Comment by gurjott** [comment]
okay I will make the changes

**Comment by gurjott** [comment]
please check, I have changed the styling and moved it to the top left.

**Comment by Tejas242** [comment]
Compare these two, and fix the styling as it was before.

before:
Screenshot_20231005_132850

After:
Screenshot_20231005_132917-1

**Pull request merged**
